# Generated by Django 2.2.17 on 2021-01-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210128_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default_img/product-img.jpg', upload_to='products_images'),
        ),
    ]
